// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectApplication.DataAccess;

#nullable disable

namespace ProjectApplication.Migrations.AuctionDb
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20231023073827_AuctionDB_UserName")]
    partial class AuctionDB_UserName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectApplication.DataAccess.AuctionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auctioneer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuctionDBs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Auctioneer = "Auctioneer 1",
                            Description = "Description 1",
                            EndDateTime = new DateTime(2023, 10, 23, 9, 38, 27, 213, DateTimeKind.Local).AddTicks(5941),
                            Name = "Auction And Bids plasce",
                            StartingPrice = 100m,
                            UserName = "user@kth.se"
                        });
                });

            modelBuilder.Entity("ProjectApplication.DataAccess.BidDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<string>("Bidder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimePlaced")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("BidDBs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Amount = 150m,
                            AuctionId = -1,
                            Bidder = "Bidder1 ",
                            TimePlaced = new DateTime(2023, 10, 23, 9, 38, 27, 213, DateTimeKind.Local).AddTicks(6109)
                        },
                        new
                        {
                            Id = -2,
                            Amount = 200m,
                            AuctionId = -1,
                            Bidder = "Bidder 2",
                            TimePlaced = new DateTime(2023, 10, 23, 9, 38, 27, 213, DateTimeKind.Local).AddTicks(6112)
                        });
                });

            modelBuilder.Entity("ProjectApplication.DataAccess.BidDB", b =>
                {
                    b.HasOne("ProjectApplication.DataAccess.AuctionDB", "AuctionDB")
                        .WithMany("BidDBs")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionDB");
                });

            modelBuilder.Entity("ProjectApplication.DataAccess.AuctionDB", b =>
                {
                    b.Navigation("BidDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
